spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      bootstrap-servers: localhost:9092
      group-id: mrcr_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


  datasource:
    url: jdbc:postgresql://localhost:5432/mrcr_db
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver

#  test:
#    topic: external.in.client-info

  sql:
    init:
      platform: postgres